# Generated by Django 2.2.5 on 2019-09-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0002_auto_20190919_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciseries',
            name='fibonacciNumber',
            field=models.CharField(max_length=3000),
        ),
    ]
